### ISSUE TITLE
Inferno should refresh the token as needed during testing

### ISSUE THREAD

**Issue by daliboz** [onc-healthit/inferno#363] opened 2019-11-25 20:14 UTC
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Today, the inferno application requires some manual driving (via the website), which can take quite a bit of time. In addition, the tests that look at all of the resource profiles themselves can take a decent amount of time. Since access tokens are recommended to have a short lifetime, it is possible that they may expire during this workflow. The inferno application should automatically refresh the token if it has expired to continue running tests.

**Your environment**
* Edition of inferno (Community or Program): Community
* Version of inferno: 2.7.0
* Which browser and version(s) is the bug present on?: I'm on Chrome, but do not expect this to be influenced by the browser

**Steps to reproduce**
1) Select the DSTU 2 Community test suite
2) Run through tests with an authorization server that limits token lifetimes (ours is 10-15 minutes), pause between the token retrieval and "Data Access" tests for long enough for the token to expire (or have the requests take long enough for the token to expire). In my case, Inferno seemed to "get stuck" for about 5 minutes, at which point the token expired - I believe it was doing some resource validation or other tests that may not have hit our server directly during this time.
3) Tests will show that the token is being rejected (in our case, we're returning the signature expired error per the OAuth 2 specification)

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Ideally, inferno would attempt to refresh the token if it has hit the expiry as returned by that authorization server for that bearer token.

**Actual behavior**
All tests from point of expiry on fail.

**Comment by Jammjammjamm** [comment] 2019-11-26 19:24
This is definitely an important issue and I will create a ticket to address it.

Do you happen to have any insight into what clients do in practice to handle token expiration? For instance do they refresh preemptively rather than react to authentication failures caused by expired tokens?

**Comment by daliboz** [comment] 2019-11-28 19:48
I've seen it handled both ways (looking for the specific error or ahead of time). However, I would recommend renewing within 1 minute before expiry.

**Comment by Jammjammjamm** [comment] 2019-12-31 19:31
This issue was addressed by #395, which has not yet been deployed. Refresh tokens will be refreshed if they will expire in under a minute, or immediately if the expiration time is unknown.

**Comment by yunwwang** [comment] 2020-10-12 14:55
Fix is released on v2.9.0

**Closed by yunwwang** 2020-10-12 14:55 UTC
Labels: awaiting release
